version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: "postgres"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      # - eli-db:/var/lib/postgresql/data
      - ./sql/01-init-db.sql:/docker-entrypoint-initdb.d/01-init-db.sql
    ports:
      - 5432:5432
    restart: unless-stopped
# volumes:
#   eli-db:

