version: '3.9'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "postgres"
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    # volumes:
    #   - db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
# volumes:
#   db:
#     external: true
