name: Create Release Tag

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for version changes
        id: version_check
        run: |
          previous_version=$(git show ${{ github.event.pull_request.base.sha }}:version.txt)
          current_version=$(cat version.txt)
          echo "::set-output name=previous_version::$previous_version"
          echo "::set-output name=current_version::$current_version"
          echo "$previous_version"
          echo "$current_version"
          echo "${{ github.event.pull_request.base.sha }}"

      - name: Create tag and release
        id: create_tag_release
        if: ${{ steps.version_check.outputs.previous_version != steps.version_check.outputs.current_version }}
        run: |
          git tag v${{ steps.version_check.outputs.current_version }}
          git push --tags